global:
  config_version: 3
input:
  type: file
  paths:
    - /var/log/vineyard/vineyard.*.log.INFO.*
    - /var/log/vineyard/vineyard_client.*.log.INFO.*
  readall: false
  fail_on_missing_logfile: false
imports:
grok_patterns:
  - 'BASE10NUM (?<![0-9.+-])(?>[+-]?(?:(?:[0-9]+(?:\.[0-9]+)?)|(?:\.[0-9]+)))'
  - 'NUMBER (?:%{BASE10NUM})'
  - 'USERNAME [a-zA-Z0-9._-]+'
  - 'LABEL [a-zA-Z._-]+'
  - 'TYPENAME [a-zA-Z\:\<\>]+'
metrics:
  - type: counter
    name: data_requests_total
    help: Number of GetData or CreateData requests
    match: '%{USERNAME:user} %{LABEL:op} data_requests_total %{NUMBER:val}'
    value: '{{.val}}'
    labels:
      user: '{{.user}}'
      operation: '{{.op}}'
  - type: counter
    name: llm_kv_cache_request_total
    help: Number of Update/BatchedUpdate or Query/BatchedQuery requests
    match: '%{USERNAME:user} %{LABEL:op} %{LABEL:status} llm_kv_cache_request_total %{NUMBER:val}'
    value: '{{.val}}'
    labels:
      user: '{{.user}}'
      operation: '{{.op}}'
      status: '{{.status}}'
  - type: summary
    name: data_request_duration_microseconds
    help: Data request duration microseconds.
    match: '%{USERNAME:user} %{LABEL:op} data_request_duration_microseconds %{NUMBER:val}'
    value: '{{.val}}'
    quantiles: {0.5: 0.05, 0.9: 0.01, 0.99: 0.001}
    labels:
      user: '{{.user}}'
      operation: '{{.op}}'
  - type: summary
    name: etcd_request_duration_microseconds
    help: etcd request duration microseconds.
    match: '%{USERNAME:user} %{LABEL:op} etcd_request_duration_microseconds %{NUMBER:val}'
    value: '{{.val}}'
    quantiles: {0.5: 0.05, 0.9: 0.01, 0.99: 0.001}
    labels:
      user: '{{.user}}'
      operation: '{{.op}}'
  - type: summary
    name: llm_kv_cache_request_duration_microseconds
    help: LLM KV cache request duration microseconds.
    match: '%{USERNAME:user} %{LABEL:op} llm_kv_cache_request_duration_microseconds %{NUMBER:val}'
    value: '{{.val}}'
    quantiles: {0.5: 0.05, 0.9: 0.01, 0.99: 0.001}
    labels:
      user: '{{.user}}'
      operation: '{{.op}}'
  - type: summary
    name: llm_kv_cache_request_nr_tokens
    help: Number of tokens involved in the LLM KV cache request
    match: '%{USERNAME:user} %{LABEL:op} llm_kv_cache_request_nr_tokens %{NUMBER:val}'
    value: '{{.val}}'
    quantiles: {0.5: 0.05, 0.9: 0.01, 0.99: 0.001}
    labels:
      user: '{{.user}}'
      operation: '{{.op}}'
  - type: gauge
    name: instances_total
    help: Number of instances in the cluster
    match: '%{USERNAME:user} instances_total %{NUMBER:val}'
    value: '{{.val}}'
    cumulative: false
    labels:
      user: '{{.user}}'
  - type: gauge
    name: instances_memory_usage_bytes
    help: Memory usage of each instance in bytes
    match: '%{USERNAME:user} %{NUMBER:instance_id} instances_memory_usage_bytes %{NUMBER:val}'
    value: '{{.val}}'
    cumulative: false
    labels:
      user: '{{.user}}'
      instance: '{{.instance_id}}'
  - type: gauge
    name: ipc_connection_total
    help: Total number of ipc connections for each instance
    match: '%{USERNAME:user} %{NUMBER:instance_id} ipc_connection_total %{NUMBER:val}'
    value: '{{.val}}'
    cumulative: true
    labels:
      user: '{{.user}}'
      instance: '{{.instance_id}}'
  - type: gauge
    name: rpc_connection_total
    help: Total number of rpc connections for each instance
    match: '%{USERNAME:user} %{NUMBER:instance_id} rpc_connection_total %{NUMBER:val}'
    value: '{{.val}}'
    cumulative: true
    labels:
      user: '{{.user}}'
      instance: '{{.instance_id}}'
  - type: gauge
    name: objects_total
    help: Total number of objects each type
    match: '%{USERNAME:user} %{NUMBER:instance_id} "%{TYPENAME:typename}" object %{NUMBER:val}'
    value: '{{.val}}'
    cumulative: true
    labels:
      user: '{{.user}}'
      instance: '{{.instance_id}}'
      type: '{{.typename}}'
server:
  protocol: http
  host: 0.0.0.0
  port: 9144
  path: /metrics
